### PR TITLE
code: fix peak times in comparison chart

### PR DESCRIPTION
**Pull request by guscost**

### CODE REVIEW

**Comment by 1egoman** [comment]
@guscost Be sure to update https://confluence.density.io/pages/viewpage.action?spaceKey=WMA&title=Report+Definitions+v1 prior to merging!

**Comment by guscost** [comment]
Left a comment, but the definition is pretty vague. I don't agree with this "fixed" method either, but am happy to copy out that comment into the definition somewhere.

**Comment by 1egoman** [comment]
Ok, can you update the definition once you've come to something that you're satisfied with? I'm trying to minimize as much as possible drift between that document and the code that goes along with it.

**Comment by guscost** [comment]
Yes, I think leaving it as a comment for now is OK, since this document (and our analytical methods for these reports) may still be evolving for some time.

**Comment by guscost** [comment]
OK, updating the description instead.

**Pull request merged**
