### PR TITLE
Remove user input for pen-test findings

### PR DESCRIPTION
**Pull request by beweinreich**

### CODE REVIEW

**Comment by beweinreich** [comment]
> Looks good. We should also remove the email field from the encoded data passed to this page too while we're at it.

Hmm I'm not seeing it? We can punt for now, but I'll create a JIRA once I know what ya mean.

**Comment by 1egoman** [comment]
@beweinreich What I mean is this: https://github.com/DensityCo/dashboard/pull/183/files#diff-7676dde7da5c1da99d3bfcc6a488f4b1R26

In this data, we have encoded an `email` value. You removed the only place where it was used, and therefore, we can remove the field from the data that the core api generates.

**Comment by 1egoman** [comment]
@beweinreich What I mean is this: https://github.com/DensityCo/dashboard/pull/183/files#diff-7676dde7da5c1da99d3bfcc6a488f4b1R26

In this data, we have encoded an `email` value. You removed the only place where it was used, and therefore, we can remove the field from the data that the core api generates.

**Comment by beweinreich** [comment]
Got it. Will remove that as well

**Pull request merged**
